<?php

declare(strict_types=1);

namespace Cresset\Magequery;

// GENERATED by scripts/publish-composer-branch.sh — the magequery binary
// version this Composer package installs. Always matches the package's git
// tag, so `composer require cresset/magequery:0.1.0` fetches the
// magequery-v0.1.0 binary.
const MAGEQUERY_VERSION = '0.1.0';
