<?php

declare(strict_types=1);

namespace Cresset\Magequery;

// GENERATED by scripts/publish-composer-branch.sh — the magequery binary
// version this Composer package installs. Always matches the package's git
// tag.
const MAGEQUERY_VERSION = '0.3.0';
